# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/aherce2/ECE-385---Final-Project/tanks/tanks.srcs/sources_1/ip/tank1_life/tank1_life.xci
# IP: The module: 'tank1_life' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/aherce2/ECE-385---Final-Project/tanks/tanks.gen/sources_1/ip/tank1_life/tank1_life_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tank1_life'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/aherce2/ECE-385---Final-Project/tanks/tanks.srcs/sources_1/ip/tank1_life/tank1_life.xci
# IP: The module: 'tank1_life' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/aherce2/ECE-385---Final-Project/tanks/tanks.gen/sources_1/ip/tank1_life/tank1_life_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tank1_life'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
